name = input("Enter Your Name :")
gpa = input ("Enter Ypur Gpa :")
age = input ("Enter your age :")
print(" ")
print ("Student Information")
print ("-----------------")
print("Name :"+name)
print("Age :"+age)
print("Gpa :"+gpa)